### PR TITLE
2 fix code

### LINKED ISSUE #2: Fix code
It is currently not possible to shim anything!

### LINKED ISSUE #3: Add support for netstandard2.0

### LINKED ISSUE #4: Expand testing
We need tests for shimming a:

- [x] instance method
- [x] Specific instance methods (should verify that we only shim methods for *that* specific instance)
- [x] Static method
- [x] Getter
- [x] Setter
- [x] ref type constructor
- [x] value type constructor (is this possible)
- [x] abstract type (method + constructor?)

At the same time we could update the tests to a more modern test framework

~The "hierarchy" of tests is as follows:~

Please see alternate hierarchy below. 

_Note: Assume that all members are public._

1. Static methods
3. Static properties
2.1 Getters
2.2 Setters
4. Methods on reference type
3.1 Methods on any instance
3.2 Methods on specific instance
3.3 Methods on abstract reference type
5. Methods on value types
4.1 Methods on any instance
~4.2 Methods on specific instance~ _This is not supported! It's only here for completeness sake._
6. Constructors
5.1 Reference types
5.2 Value types

There is the following alternate hierarchy (which I might be more partial to):

## Isolation
These tests exercise the entire library via `PoseContext.Isolate`. 

## Shimming
_Note: These tests should be renamed to "Isolation"._
These are the full-blown tests which test the entire stack. 

We want to test the following:

1. Methods
1.1 Static types
1.2 Reference types
1.2.1 Any instance
1.2.2 Specific instance
1.3 Value types
1.3.1 Any instance
~1.3.2 Specific instance of value type~ _This is not supported! It's only here for completeness sake._
1.4 Abstract methods
1.5 Sealed types (both reference and value types)
2. Getters
2.1 Static types
2.2 Reference types
2.2.1 Any instance
2.2.2 Specific instance
2.3 Value types
2.3.1 Any instance
2.3.2 Specific instance (_Is this supported?_)
2.4 Sealed types (both reference and value types)
3. Setters
3.1 Static types
3.2 Reference types
3.2.1 Any instance
3.2.2 Specific instance
3.3 Value types
3.3.1 Any instance
3.3.2 Specific instance (_Is this supported?_)
3.4 Sealed types (both reference and value types)
4. Constructors
~4.1 Static types~ _Not currently possible_
4.2 Reference types
~4.3 Value types~ _It seems this isn't supported_
4.4 Sealed types (both reference and value types)

## Method rewriting
These tests should only be concerned with rewriting methods. 
We wants to test for:

- Rewriting static methods
- Rewriting instance methods of reference types
- Rewriting instance methods of value types
- Rewriting abstract methods
- Rewriting unsafe methods _Note that this is in an ideal world. See #9_
- Rewriting async methods _See #12_
- Not being able to rewrite methods in System.Private.CoreLib

## IL generation (via stubs)
These tests are concerned with generating IL for stubs (which will later be used to inject the shims). 

We want to test that we can generate stubs for:

- Direct calls
- Virtual calls
  - Including for a constrained type (What does this mean?)
- Object initialization (constructor invocations)
- Direct load (What does this mean?)
- Virtual load (What does this mean?)

## Other
These tests I have not been able to put into any specific category. They are therefore lumped together here. 

We want to test the following:
- That we can correctly determine whether a method is in System.Private.CoreLib (both positive and negative verification)
- That we can verify whether a method is an override (both positive and negative verification)

### LINKED ISSUE #6: Fix tests for net6.0
For some reason the test "Can_rewrite_static_method" seems to fail only when targeting net6.0 or greater. 

It seems to be caused by not handling InlineSig opcode. 

This was also reported here: tonerdo/pose#30

### LINKED ISSUE #8: Add support for .NET 8
The sample app (Sandbox) worked when targeting .NET 7.0 (`DateTime.Now` returning a timestamp in the year 2004). I have not conducted extensive testing, though.

The same app failed to run when targeting .NET 8.0 due to the `Bake...` array method.

_Originally posted by @stanimirsellercloud in https://github.com/Miista/pose/issues/5#issuecomment-1890438600_

### PR DESCRIPTION
**Pull request by Miista**
Closes #2 
Closes #3

### CODE REVIEW

**Comment by stoyanov-x** [comment]
It's great to see this work on .NET 7.0.

However, it looks like the `Bake...` method is missing or otherwise cannot be used in a .NET 8.0 scenario.

Do you have a plan to support this?

**Comment by Miista** [comment]
@stanimirsellercloud Are you thinking of the `BakeArray` method?

I will definitely look into what alternatives there are. 

Maybe that's why the tests are failing on net6+. I'm tracking that in #6.

**Comment by Miista** [comment]
@stanimirsellercloud You said it was "great to see [it] work on .NET 7.0". Did you test it on .NET 7.0?

**Comment by stoyanov-x** [comment]
The sample app (Sandbox) worked when targeting .NET 7.0 (`DateTime.Now` returning a timestamp in the year 2004). I have not conducted extensive testing, though.

The same app failed to run when targeting .NET 8.0 due to the `Bake...` array method.

**Comment by Miista** [comment]
I will look into it. Thank you for bringing it up. I'm tracking it in #8.

**Comment by Miista** [comment]
@stanimirsellercloud I've fixed the issue. Please see my comment on #8

**Pull request merged**
